### PR TITLE
[native_toolchain_c] Forced includes

### LINKED ISSUE #2095: Defines with quotation marks (") break build process on Windows
Using `CBuilder.library`, on Windows, the build crashes with:

```text
'C:\Program' is not recognized as an internal or external command, operable program or batch file.

Error: Compiling native assets failed.
```

This happens because the escaping / string quoting for defines, PATH, other environment variables fails when a define has a double quotation mark in it (it's possible this will apply to flags as well)

```dart
import 'package:logging/logging.dart';
import 'package:native_assets_cli/code_assets.dart';
import 'package:native_toolchain_c/native_toolchain_c.dart';

void main(List<String> args) async {
  final packageName = input.packageName;
  await build(args, (input, output) async {
    var defines = <String, String>{
      'WORKING_DEFINE': "'VAL'",
      'BROKEN_DEFINE': '"VAL"',
    };

    final builder = CBuilder.library(
      name: packageName,
      assetName: '$packageName.dart',
      pic: true,
      std: 'c++17',
      sources: [
         // ...
      ],
      language: Language.cpp,
      includes: [
        // ...
      ],
      defines: defines,
    );

    await builder.run(
        input: input,
        output: output,
        logger: Logger('')
          ..level = Level.ALL
          ..onRecord.listen((record) => print(record.message)));
  });
}

### PR DESCRIPTION
**Pull request by zeyus**
Fix #2095 

- This PR addresses the issue https://github.com/dart-lang/native/issues/2095 where defines that include double quotation marks would break the command-line execution using `CL.EXE`

**How it works**

`CBuilder.libaray` and `CBuilder.executable` take a new optional argument `forcedIncludes` which is a list of file paths to source files, these source files, if defined will be prepended by the compiler to each source.

In `clang`, this uses the `-include<file>` argument, in `CL.exe` this uses the `/FI<file>` argument. See the related issue: https://github.com/dart-lang/native/issues/2095

I'm currently on OSX so I haven't run the test on windows yet

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

File: pkgs/native_toolchain_c/lib/src/cbuilder/ctool.dart [hunk 1]
```diff
@@ -46,6 +46,14 @@ abstract class CTool {
   /// The sources will be reported as dependencies of the hook.
   final List<String> includes;
 
+  /// Files passed to the compiler that will be included before all source
+  /// files.
+  ///
+  /// Resolved against [LinkInput.packageRoot].
+  ///
+  /// The sources will be reported as dependencies of the hook.
+  final List<String> forcedIncludes;
```
Comment (dcharkes) [inline pkgs/native_toolchain_c/lib/src/cbuilder/ctool.dart:55]: Maybe add a link to a microsoft and clang documentation page.

File: pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart [hunk 2]
```diff
@@ -121,7 +121,6 @@ void main() async {
             output: buildOutput,
             logger: logger,
           );
-
```
Comment (dcharkes) [inline pkgs/native_toolchain_c/test/cbuilder/cbuilder_cross_windows_host_test.dart:124]: spurious edit

**Review by dcharkes — APPROVED** [review]
LGTM! 🚀

File: pkgs/native_toolchain_c/lib/src/cbuilder/ctool.dart (hunk 1 above)
Comment (zeyus) [reply pkgs/native_toolchain_c/lib/src/cbuilder/ctool.dart:59]: Added links in the documentation for the focedIncludes prop.

File: pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart [hunk 3]
```diff
@@ -278,6 +282,8 @@ void main() {
     final result = await runProcess(executable: executableUri, logger: logger);
     expect(result.exitCode, 0);
     expect(result.stdout, contains('Macro FOO is defined: USER_FLAG'));
+    // check the forced include is added
```
Comment (dcharkes) [inline pkgs/native_toolchain_c/test/cbuilder/cbuilder_test.dart:285]: Nit: punctuation. Start comment with a capital and end with a period.

**Review by dcharkes — APPROVED** [review]
1 more nit, and we're good to go! Thanks! 🚀
