### PR TITLE
[jni] Clarify `JBuffer.array` docs

### LINKED ISSUE #1920: Incorrect implementation of `JByteBuffer.array`
This is with:
```
dependencies:
  jni: ^0.13.0
```

Repro:

```dart
import 'dart:typed_data';
import 'package:jni/jni.dart';

void main() {
    final l = Uint8List.fromList([1, 2, 3, 4]);
    final bb = JByteBuffer.fromList(l);

    print(l);
    print(bb.array);
    print(bb.array.getRange(0, 4));
}


Output:

```
[1, 2, 3, 4]
(0, 0, 0, 0, 1, 2, 3, 4, 0, 0, 0)
[0, 0, 0, 0]
```

### PR DESCRIPTION
**Pull request by HosseinYousefi**
Closes #1920.

Clarifies that the `arrayOffset` is needed when extracting the elements from the `array` of a `JBuffer`.

### CODE REVIEW

File: pkgs/jni/lib/src/nio/jbuffer.dart [hunk 1]
```diff
@@ -246,9 +246,15 @@ class JBuffer extends JObject {
 
   /// The array that backs this buffer.
   ///
+  /// Note that the first element of the buffer start at element [arrayOffset]
```
Comment (dcharkes) [inline pkgs/jni/lib/src/nio/jbuffer.dart:249]: Grammar

**Review by dcharkes — APPROVED** [review]
