### PR TITLE
[ffigen] Fix flaky tests

### LINKED ISSUE #1435: [ffigen][objective_c] test/native_objc_test/global_test.dart flaky
While reviewing https://github.com/dart-lang/native/pull/1434/:

```
00:03 +13 -1: test/native_objc_test/automated_ref_count_test.dart: Automatic reference counting assign properties ref count correctly [E]                                                                                                                                                   
  Expected: <1>
    Actual: <0>
```

After rerunning the test passed.

cc @liamappelbe

### PR DESCRIPTION
**Pull request by liamappelbe**
Fixes #1435

### CODE REVIEW

**Comment by liamappelbe** [comment]
Can't repro the global test failures locally. Hopefully this fix works?

File: pkgs/ffigen/test/native_objc_test/arc_test.dart [hunk 1]
```diff
@@ -97,6 +92,10 @@ void main() {
       expect(objectRetainCount(obj2raw), 3);
       expect(objectRetainCount(obj3raw), 2);
 
+      expect(obj1, isNotNull); // Force obj1 to stay in scope.
```
Comment (HosseinYousefi) [inline pkgs/ffigen/test/native_objc_test/arc_test.dart:95]: This would not be needed if the objects are `Finalizable`, but objects being `Finalizable` make them non-sharable. 
So maybe we need the "`StayAlive`" marker interface @dcharkes!

In JNIgen I don't have a direct `.pointer` getter, instead users have to write `.reference.pointer` maybe that fixes the issue? I wonder if that works as `.reference` is used in the scope and is `Finalizable` but `Pointer` is not `Finalizable`.

**Review by HosseinYousefi — APPROVED** [review]
LGTM! We might want to change stuff so objects somehow stay in scope until the end of the block.

File: pkgs/ffigen/test/native_objc_test/arc_test.dart (hunk 1 above)
Comment (liamappelbe) [reply pkgs/ffigen/test/native_objc_test/arc_test.dart:95]: I'm not worried about it. This is only an issue in these tests, where I'm explicitly testing the GC behavior. I don't think this will matter to users.

Comment (HosseinYousefi) [reply pkgs/ffigen/test/native_objc_test/arc_test.dart:95]: I am worried about it lol! We had this GC problem in `package:jni` that happened in user code randomly.

Comment (liamappelbe) [reply pkgs/ffigen/test/native_objc_test/arc_test.dart:95]: Interesting. How did it manifest for users? I haven't been able to think of a situation where it would matter, other than tests like this.
