### PR TITLE
[native_assets_builder] Stop throwing from BuildRunner

### LINKED ISSUE #106: [native_assets_builder] Output a success bool and don't throw
When more than one package with native assets has a build failure, throwing an error on the first build failure is unhelpful.

If we provide an interface of what we return from `BuildRunner` we can add a list of errors.

> We should add some API that we can extend later. (Most likely we'd also want some way to display the errors in flutter_tools on builds that fail rather than rely on only streaming logs in the context of https://github.com/dart-lang/native/issues/33.)

https://github.com/dart-lang/native/issues/105#issue-1830955236

### LINKED ISSUE #111: [native_assets_builder] Caching logic on build failures
Is this caching logic only used when the last build was actually successfull?

_Originally posted by @mkustermann in https://github.com/dart-lang/native/pull/107#discussion_r1281867228_
            
Currently, the caching logic for native builds is based on the `build_output.yaml`. That can however lead to strange failures. For example if the `build_output.yaml` is a valid file, but the build terminated with a non-zero exit code, then a subsequent build invocation would succeed.

### PR DESCRIPTION
**Pull request by dcharkes**
Closes #106.

* Streams errors to the logger.
* Returns a `success` boolean.

Closes #111.

* Deletes `build_output.yaml` to prevent caching on build failures. (See issue for alternative solutions.)

### CODE REVIEW

File: pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart [hunk 1]
```diff
@@ -56,34 +54,39 @@ class NativeAssetsBuildRunner {
...
+          workingDirectory,
+          includeParentEnvironment,
+        );
+      }
     }
-    return assetList;
+    return _BuildResultImpl(
+      assets: _assets,
+      dependencies: _dependencies..sort(_uriCompare),
+      errors: _errors,
```
Comment (mkustermann) [inline pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart:88]: See comments on https://github.com/dart-lang/native/pull/107#pullrequestreview-1558947579

**Comment by mkustermann** [comment]
@dcharkes given you want to rely on logging as side-channel for any build related info (what is being build, whether it was successful or not, reproduction instructions, timings, ...) it seems this PR isn't needed, is it?

**Comment by dcharkes** [comment]
> @dcharkes given you want to rely on logging as side-channel for any build related info (what is being build, whether it was successful or not, reproduction instructions, timings, ...) it seems this PR isn't needed, is it?

I still think it's a good idea to return a success boolean rather than throwing and having call sites catch or write `onError` on the futures. (That's way it's less likely that launchers will forget to handle errors and throw a stack trace at the user.)

**Comment by dcharkes** [comment]
@mkustermann I've reworked the PR so that it doesn't throw any errors anymore and streams all errors to the logger.

File: pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart [hunk 2]
```diff
@@ -51,44 +51,54 @@ class NativeAssetsBuildRunner {
       rootPackageRoot: packageLayout.rootPackageRoot,
       packagesWithNativeAssets: packagesWithNativeAssets,
       dartExecutable: Uri.file(Platform.resolvedExecutable),
+      logger: logger,
     );
-    final plan = planner.plan();
+    final (plan, planSuccess) = planner.plan();
```
Comment (mkustermann) [inline pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart:56]: Consider having an early return `if (!planSuccess)`

File: pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart [hunk 3]
```diff
@@ -112,32 +122,38 @@ class NativeAssetsBuildRunner {
...
```
Comment (mkustermann) [inline pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart:127]: ditto

File: pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart [hunk 4]
```diff
@@ -193,25 +209,77 @@ class NativeAssetsBuildRunner {
...
+build_output.yaml contained a format error.
+${e.message}
+        ''');
+      success = false;
+      return (<Asset>[], <Uri>[], Metadata({}), false);
+      // TODO(https://github.com/dart-lang/native/issues/109): Stop throwing
+      // type errors in native_assets_cli, release a new version of that package
+      // and then remove this.
+      // ignore: avoid_catching_errors
+    } on TypeError {
```
Comment (mkustermann) [inline pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart:267]: `TypeError`s are usually incorrect programs. Does the yaml logic use that type for exceptions? Maybe it can rather throw a `YamlParseError` or something like that?

**Review by mkustermann — APPROVED** [review]

File: pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart (hunk 4 above)
Comment (dcharkes) [reply pkgs/native_assets_builder/lib/src/build_runner/build_runner.dart:267]: https://github.com/dart-lang/native/issues/109 tracks this issue. (The issue is in a dependency. Since we have published dependencies, fixing it in the same PR doesn't help, because we'd need to merge first and then publish and then merge this package.)

**Comment by dcharkes** [comment]
Thanks @mkustermann !
