### PR TITLE
[jni] Improve error message when JNI used too early

### LINKED ISSUE #2872: [jnigen] SIGSEGV with JNIgen/federated plugin
### Steps to reproduce
Repo reproduction:
https://github.com/davidhicks980/jnigen_federated_plugin_bug

Run packages/demo_plugin/example -> should throw immediately
Run packages/demo_plugin_android/example -> should throw immediately

Comment out `dartPluginClass: DemoPluginAndroid` on demo_plugin_android/pubspec.yaml
`flutter clean` from both examples

Run packages/demo_plugin/example -> should not throw; should run kotlin code correctly
Run packages/demo_plugin_android/example -> should not throw; should run kotlin code correctly

Error from vscode:

```cmd
Installing build/app/outputs/flutter-apk/app-debug.apk...           3.3s
D/FlutterJNI(11562): Beginning load of flutter...
D/FlutterJNI(11562): flutter (null) was loaded normally!
I/flutter (11562): [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(62)] Using the Impeller rendering backend (Vulkan).
I/flutter (11562): [IMPORTANT:flutter/shell/platform/android/android_context_gl_impeller.cc(104)] Using the Impeller rendering backend (OpenGLES).
Error initializing DevFS: DevFSException(Service disconnected, _createDevFS: (-32000) Service connection disposed, null)
Lost connection to device.
```

Error from Android Studio

```cmd
2025-12-18 18:28:36.323 12949-12949 libc                    com.demo.demo.plugin.example         A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 12949 (.plugin.example), pid 12949 (.plugin.example)
2025-12-18 18:28:36.601 13003-13003 DEBUG                   pid-13003                            A  Cmdline: com.demo.demo.plugin.example
2025-12-18 18:28:36.601 13003-13003 DEBUG                   pid-13003                            A  pid: 12949, tid: 12949, name: .plugin.example  >>> com.demo.demo.plugin.example <<<
2025-12-18 18:28:36.602 13003-13003 DEBUG                   pid-13003                            A        #00 pc 000000000000c9bc  /data/app/~~jtlLS-fLCo8yt1_6ldAvfQ==/com.demo.demo.plugin.example-1RKEOg9HpmUloLFMk88yoA==/base.apk!libdartjni.so (BuildId: 13a717027dc65e5412a692b65c8c316ae3e1af99)
2025-12-18 18:28:36.602 13003-13003 DEBUG                   pid-13003                            A        #01 pc 000000000000b3e8  /data/app/~~jtlLS-fLCo8yt1_6ldAvfQ==/com.demo.demo.plugin.example-1RKEOg9HpmUloLFMk88yoA==/base.apk!libdartjni.so (FindClassUnchecked+28) (BuildId: 13a717027dc65e5412a692b65c8c316ae3e1af99)
2025-12-18 18:28:36.602 13003-13003 DEBUG                   pid-13003                            A        #02 pc 000000000000b594  /data/app/~~jtlLS-fLCo8yt1_6ldAvfQ==/com.demo.demo.plugin.example-1RKEOg9HpmUloLFMk88yoA==/base.apk!libdartjni.so (FindClass+48) (BuildId: 13a717027dc65e5412a692b65c8c316ae3e1af99)
```

### Context

I apologize for using a repo as an example, but for some context:

I filed an issue on the plugin platform interface, since I thought this was related to federated plugins: https://github.com/flutter/flutter/issues/180102

However, @stuartmorgan-g mentioned this is probably not the case:

https://github.com/flutter/flutter/issues/180102#issuecomment-3675783448

I'm completely new to federated plugins and JNIgen, so this could be a user error on my part.

The bit that is confusing me is that if you comment out `dartPluginClass: DemoPluginAndroid`, you can directly call the android plugin from packages/demo_plugin_android/example, and it will call the kotlin code correctly:

```dart
void main() {
  // This will work without an error
  final value = DemoPluginAndroid().callback();
  print(value);
  runApp(const MyApp());
}
```

This is why I'm curious whether the federated plugin mechanism is somehow related. 

### Logs

<details open><summary>Logs</summary>

```console
2025-12-18 18:28:36.323 12949-12949 libc                    com.demo.demo.plugin.example         A  Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 12949 (.plugin.example), pid 12949 (.plugin.example)
2025-12-18 18:28:36.601 13003-13003 DEBUG                   pid-13003                            A  Cmdline: com.demo.demo.plugin.example
2025-12-18 18:28:36.601 13003-13003 DEBUG                   pid-13003                            A  pid: 12949, tid: 12949, name: .plugin.example  >>> com.demo.demo.plugin.example <<<
2025-12-18 18:28:36.602 13003-13003 DEBUG                   pid-13003                            A        #00 pc 000000000000c9bc  /data/app/~~jtlLS-fLCo8yt1_6ldAvfQ==/com.demo.demo.plugin.example-1RKEOg9HpmUloLFMk88yoA==/base.apk!libdartjni.so (BuildId: 13a717027dc65e5412a692b65c8c316ae3e1af99)
2025-12-18 18:28:36.602 13003-13003 DEBUG                   pid-13003                            A        #01 pc 000000000000b3e8  /data/app/~~jtlLS-fLCo8yt1_6ldAvfQ==/com.demo.demo.plugin.example-1RKEOg9HpmUloLFMk88yoA==/base.apk!libdartjni.so (FindClassUnchecked+28) (BuildId: 13a717027dc65e5412a692b65c8c316ae3e1af99)
2025-12-18 18:28:36.602 13003-13003 DEBUG                   pid-13003                            A        #02 pc 000000000000b594  /data/app/~~jtlLS-fLCo8yt1_6ldAvfQ==/com.demo.demo.plugin.example-1RKEOg9HpmUloLFMk88yoA==/base.apk!libdartjni.so (FindClass+48) (BuildId: 13a717027dc65e5412a692b65c8c316ae3e1af99)
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel master, 3.40.0-1.0.pre-165, on macOS 15.5 24F74 darwin-arm64, locale en-US) [2.3s]
    • Flutter version 3.40.0-1.0.pre-165 on channel master at /Users/davidhicks/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 331cdce7b5 (4 days ago), 2025-12-15 09:21:26 +1300
    • Engine revision 331cdce7b5
    • Dart version 3.11.0 (build 3.11.0-242.0.dev)
    • DevTools version 2.53.0
    • Feature flags: enable-web, enable-linux-desktop, enable-macos-desktop, enable-windows-desktop, enable-android, enable-ios,
      cli-animations, enable-native-assets, omit-legacy-version-file, enable-lldb-debugging, enable-uiscene-migration

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0) [2.9s]
    • Android SDK at /Users/davidhicks/Library/Android/sdk
    • Emulator version 36.3.10.0 (build_id 14472402) (CL:N/A)
    • Platform android-36, build-tools 35.0.0
    • ANDROID_HOME = /Users/davidhicks/Library/Android/sdk
    • Java binary at: /Users/davidhicks/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home/bin/java
      This JDK is specified in your Flutter configuration.
      To change the current JDK, run: `flutter config --jdk-dir="path/to/jdk"`.
    • Java version OpenJDK Runtime Environment JBR-17.0.14+1-1367.22-nomod (build 17.0.14+1-b1367.22)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 16.4) [1,722ms]
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16F6
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web [7ms]
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Connected device (3 available) [7.0s]
    • SM G975U1 (wireless) (mobile) • adb-R58M23AEHEX-T1Qoe1._adb-tls-connect._tcp • android-arm64  • Android 12 (API 31)
    • macOS (desktop)               • macos                                        • darwin-arm64   • macOS 15.5 24F74 darwin-arm64
    • Chrome (web)                  • chrome                                       • web-javascript • Google Chrome 143.0.7499.110
    ! Error: Browsing on the local area network for David’s iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources [218ms]
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by liamappelbe**
If JNI is used (eg by a user invoking a JNIgen Java API) before Flutter's plugin initialization, this manifests as `jni->jvm` being `NULL`. Detect this and log a nicer error message before the inevitable crash.

Fixes https://github.com/dart-lang/native/issues/2872

### CODE REVIEW

File: pkgs/jni/src/dartjni.h [hunk 1]
```diff
@@ -152,6 +158,10 @@ static inline void detach_thread(void* data) {
 
 static inline void attach_thread() {
   if (jniEnv == NULL) {
+    if (jni->jvm == NULL) {
+      LOGF("JNI is not initialized. Are you trying to invoke a Java API"
+        " too early, before Flutter plugin initialization?");
```
Comment (davidhicks980) [inline pkgs/jni/src/dartjni.h]: It may be helpful to indicate how the user can determine if Flutter plugins have been initialized.

Comment (liamappelbe) [reply pkgs/jni/src/dartjni.h]: I'm not sure what the best practice recommendation would be for that. @stuartmorgan-g Any suggestions for what we should tell users in this error message?

**Review by dcharkes — APPROVED** [review]

File: pkgs/jni/src/dartjni.h (hunk 1 above)
Comment (stuartmorgan-g) [reply pkgs/jni/src/dartjni.h]: Ideally we should tell them exactly when they can call it (I don't even know what "plugin initialization" means precisely here, so probably nobody else does either). What is the thing that sets up `jni->jvm` specifically?

Comment (liamappelbe) [reply pkgs/jni/src/dartjni.h]: There's a `JniPlugin` class in package:jni that has a [static initializer block](https://github.com/dart-lang/native/blob/main/pkgs/jni/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java#L22) that does it. That initializer block is run the first time the class is interacted with (presumably when Flutter instantiates the `JniPlugin` class). I'm not sure when exactly that is in relation to the user's Dart code.

Comment (stuartmorgan-g) [reply pkgs/jni/src/dartjni.h]: In that case we probably don't want to try to pinpoint the exact timing, since people shouldn't generally need to know about engine bringup order. Maybe we should say "before 'main' (such as during Dart plugin class registration)" to cover the known case?

I definitely don't think we should just say "before plugin initialization", because the place where it was failing in the linked issue was during (Dart) plugin initialization.
