### PR TITLE
[swift2objc] Support async initializers and properties

### LINKED ISSUE #1778: [swift2objc] Support async initializers and properties
Working on https://github.com/dart-lang/native/issues/1773, I found that async initializers and property getters can't be marked with `@objc`:

```
pkgs/swift2objc/test/integration/async_output.swift:36:9: error: 'async' initializer cannot be represented in Objective-C
  @objc init(y: Int) async {
        ^            ~~~~~

pkgs/swift2objc/test/integration/async_output.swift:26:20: error: property with 'throws' or 'async' is not representable in Objective-C
  @objc public var x: MyClassWrapper {
                   ^
```

Similarly to https://github.com/dart-lang/native/issues/1765, the fix is to transform these initializers and properties into a static method.

### PR DESCRIPTION
**Pull request by AmrAhmed119**
- Closes #1778 

- [x] Add Support for async getters by converting them into ordinary methods.
- [x] Add Support for async initializers by converting them into static methods. 

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

File: pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart [hunk 1]
```diff
@@ -80,3 +107,37 @@ List<String> _generateInitializerStatements(
     return ['${wrappedClassInstance.name} = $instanceConstruction'];
   }
 }
+
+List<String> _generateMethodStatements(
```
Comment (liamappelbe) [inline pkgs/swift2objc/lib/src/transformer/transformers/transform_initializer.dart:111]: This shares a lot of logic with `_generateInitializerStatements`. See if you can factorize them a bit.

**Review by liamappelbe — COMMENTED** [review]
Looks pretty good. I like that you reused the pattern from the last PR in transform_compound. I just have one smallish comment.

**Review by liamappelbe — APPROVED** [review]
