### PR TITLE
Use check:jni for tests and fix warnings

### LINKED ISSUE #1067: Always test with enabled `check:jni` and fix warnings

### PR DESCRIPTION
**Pull request by HosseinYousefi**
Closes #1067.

### CODE REVIEW

File: pkgs/jni/test/type_test.dart [hunk 1]
```diff
@@ -205,7 +205,8 @@ final class $FType extends JObjType<F> {
 void main() {
   if (!Platform.isAndroid) {
     checkDylibIsUpToDate();
-    Jni.spawnIfNotExists(dylibDir: "build/jni_libs", jvmOptions: ["-Xmx128m"]);
+    Jni.spawnIfNotExists(
+        dylibDir: "build/jni_libs", jvmOptions: ["-Xmx128m", "-Xcheck:jni"]);
```
Comment (dcharkes) [inline pkgs/jni/test/type_test.dart:209]: Should we make a helper method somewhere to ensure we have the same options everywhere?

**Review by dcharkes — APPROVED** [review]
