### PR TITLE
More quick fixes for bugs related to #1250

### LINKED ISSUE #1275: Objective-C generated code results in module redefinition
If I manually fix the issues in https://github.com/dart-lang/native/issues/1269, I get a compilation error:

```
Lexical or Preprocessor Issue (Xcode): Redefinition of module 'Foundation'
/System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Sy
stem/Library/Frameworks/Foundation.framework/Modules/module.modulemap:0:17
```

I think that is because the includes are not generated correctly:
```
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSArray.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSData.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSDictionary.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLCache.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLRequest.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLSession.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURL.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSProgress.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLResponse.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSHTTPCookieStorage.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSOperation.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSError.h"
#include "../../../../../../../System/Volumes/Data/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSDictionary.h"
```

Objective-C headers don't have header guards so I think that you need `import` rather than `include`.

Also, I'm not sure if the compiler will realize that `#import "../../foo.h"` and `#import <foo.h>` refer to the same file.

### PR DESCRIPTION
**Pull request by liamappelbe**
Fixes some more small bugs in the generated ObjC code related to listener blocks:
- Resolve naming conflicts in the ObjC wrapper functions, by adding infra to run the `UniqueNamer` on certain `Binding.originalName`s.
- Remove the `_Nullable` annotation from the generated ObjC code. It doesn't really do anything in our use case, and is an invalid annotation on certain types.
- Use `#import` instead of `#include`
- Use `#import <Framework/Header.h>` style imports instead of `#import "../../../Relative/Path/To/Framework/Header.h"` for headers that are part of a framework.

Fixes #1275

### CODE REVIEW

File: pkgs/ffigen/lib/src/code_generator/objc_block.dart [hunk 1]
```diff
@@ -275,6 +275,7 @@ $blockTypedef $fnName($blockTypedef block) {
         objCReturnsRetained: true,
         isLeaf: true,
         isInternal: true,
+        originalNameIsRenamable: true,
```
Comment (dcharkes) [inline pkgs/ffigen/lib/src/code_generator/objc_block.dart:278]: I wonder if this is the right approach.

Conceptually any original names (from the source language) should not be renameable, because looking up things would fail.

Here we actually bind to some native code that we generate, so I would maybe not call that the original name.

Is there a way we can separate the concepts of (1) a name in the native source code "originalName" and (2) a name in the native source code that we generate "intermediateName". (And then "name" for what the user-uses.)

**Review by dcharkes — APPROVED** [review]
> Resolve naming conflicts in the ObjC wrapper functions, by adding infra to run the UniqueNamer on certain Binding.originalNames.

I think we should maybe introduce a third concept besides `originalName` and `name`.

File: pkgs/ffigen/lib/src/code_generator/objc_block.dart (hunk 1 above)
Comment (liamappelbe) [reply pkgs/ffigen/lib/src/code_generator/objc_block.dart:278]: We'd need a flag in `Func` to tell it whether to use the `originalName` or `intermediateName` when looking up the symbol. When considering that option I realized we can just add a flag that tells the `Func` to use the `name` instead of the `originalName` for lookup, and then we wouldn't need any extra renaming steps in the library.
