### PR TITLE
[swift2objc] fix: support optional primitives by boxing as wrapper types

### LINKED ISSUE #1743: [swift2objc] Support optional primitives
Optional object types are straightforward to support, because they map to nullable object pointers in ObjC. But for optional primitive types like `Int?`, there's no ObjC equivalent. So the swift compiler will raise an error if you try to annotate an entity involving `Int?` with `@objc`.

The straightforward solution is to box the `Int` in an object.

Dart *does* support `int?`, so ideally we'd also unbox it on the Dart side. To do this we'd need to special case the box type in ffigen.

### PR DESCRIPTION
**Pull request by TheNourhan**
## Description

Swift optional primitives like `Int?` cannot be directly represented in Objective-C. This PR boxes them using the existing primitive wrapper classes (e.g., `IntWrapper?`) so they can be used in `@objc` APIs.

## Related Issues

Fixes #1743

## PR Checklist

- [x] I’ve reviewed the [contributor guide](https://github.com/dart-lang/native/blob/main/CONTRIBUTING.md) and applied the relevant portions to this PR.
- [ ] I've run `dart tool/ci.dart --all` locally and resolved all issues identified. This ensures the PR is formatted, has no lint errors, and ran all code generators. This applies to the packages part of the toplevel `pubspec.yaml` workspace.
- [ ] All existing and new tests are passing. I added new tests to check the change I am making.
- [x] The PR is actually solving the issue. PRs that don't solve the issue will be closed. Please be respectful of the maintainers' time. If it's not clear what the issue is, feel free to ask questions on the GitHub issue before submitting a PR.
- [ ] I have updated `CHANGELOG.md` for the relevant packages. (Not needed for small changes such as doc typos).
- [ ] I have [updated the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change) if necessary.

### CODE REVIEW

File: pkgs/swift2objc/lib/src/transformer/_core/utils.dart [hunk 1]
```diff
@@ -33,6 +33,21 @@ import 'unique_namer.dart';
...
+  if (type is OptionalType) {
+    final (wrappedChildType, childIsPrimitive) = maybeGetPrimitiveWrapper(
+      type.child,
+      true,
+      state,
+    );
+    if (childIsPrimitive) {
+      final wrapperName = (wrappedChildType as DeclaredType).name;
+      return (
+        '$value == nil ? nil : $wrapperName($value!)',
```
Comment (liamappelbe) [inline pkgs/swift2objc/lib/src/transformer/_core/utils.dart:56]: Is the `!` after `$value` necessary? I would have assumed that Swift could deduce that `$value` is not `nil` there.

**Review by liamappelbe — COMMENTED** [review]
Looks pretty good. Almost ready to land as-is. Just one question.

Also, make sure to sync to head and fix the merge conflicts.

File: pkgs/swift2objc/lib/src/transformer/_core/utils.dart (hunk 1 above)
Comment (TheNourhan) [reply pkgs/swift2objc/lib/src/transformer/_core/utils.dart:56]: If I remove it, it will give different outputs:

For example, for:
`public func globalOptionalIntReturn() -> Int? { return nil }`

It will give:
```
@objc static public func globalOptionalIntReturnWrapper() -> IntWrapper? {
let result = globalOptionalIntReturn()

return result == nil ? nil : IntWrapper(result)
}
```

**Comment by TheNourhan** [comment]
> Also, make sure to sync to head and fix the merge conflicts.

Done.

File: pkgs/swift2objc/lib/src/transformer/_core/utils.dart (hunk 1 above)
Comment (liamappelbe) [reply pkgs/swift2objc/lib/src/transformer/_core/utils.dart:56]: Yeah, I'm asking about that output. Is it a problem if the generated swift code doesn't have the `!`?

Comment (TheNourhan) [reply pkgs/swift2objc/lib/src/transformer/_core/utils.dart:56]: yes, without `!`, swift gives: `error: value of optional type 'Int?' must be unwrapped to a value of type 'Int'`

Screenshot from 2026-02-26 11-52-55

Comment (liamappelbe) [reply pkgs/swift2objc/lib/src/transformer/_core/utils.dart:56]: Ok, fair enough. I guess Swift's nullability checker can't deduce that case.

**Review by liamappelbe — APPROVED** [review]
