### PR TITLE
[jnigen] Respect top-type nullability of type arguments

### LINKED ISSUE #1906: Kotlin wildcards should be generated as the class top-type
Currently they get generated as `JObject?` and if the top-type is non-nullable (or in the future has an `extends T` constraint), this will fail.

### PR DESCRIPTION
**Pull request by HosseinYousefi**
Closes #1906.

Keep the original nullability of a type argument `T extends Foo`, so that even if the type provided is not explicitly identified as nullable or non-nullable (due to a missing annotation or being a kotlin wildcard), it's still generated with regards to the constraints of the top-type `Foo`.

### CODE REVIEW

File: pkgs/jnigen/lib/src/bindings/dart_generator.dart [hunk 1]
```diff
@@ -769,38 +778,42 @@ class _TypeGenerator extends TypeVisitor<String> {
...
-      forInterfaceImplementation: forInterfaceImplementation,
-      typeErasure: forInterfaceImplementation,
-      includeNullability: true,
-      arrayType: false,
-    );
-    final definedTypeParams = node.params.accept(typeGenerator).toList();
+    final definedTypeParams = <String>[];
+    for (var i = 0; i < node.params.length; ++i) {
+      final param = node.params[i];
+      final index = allTypeParams.length - node.params.length + i;
```
Comment (liamappelbe) [inline pkgs/jnigen/lib/src/bindings/dart_generator.dart:796]: This allTypeParams stuff feels like it should be factored out into a little helper class or something. You have little bits of logic for dealing with allTypeParams indexes spread throughout this function. Better to consolidate that logic if possible.

File: pkgs/jnigen/lib/src/bindings/dart_generator.dart [hunk 2]
```diff
@@ -935,39 +962,48 @@ class _TypeClassGenerator extends TypeVisitor<_TypeClass> {
...
-        boxPrimitives: false,
-        forInterfaceImplementation: forInterfaceImplementation,
-        typeErasure: forInterfaceImplementation,
-      ),
-    );
+    final definedTypeClasses = <_TypeClass>[];
+
+    for (var i = 0; i < node.params.length; ++i) {
+      final param = node.params[i];
+      final index = allTypeParams.length - node.params.length + i;
```
Comment (liamappelbe) [inline pkgs/jnigen/lib/src/bindings/dart_generator.dart:978]: More allTypeParams stuff. If you write a helper, could it be reused here?

**Review by liamappelbe — APPROVED** [review]

File: pkgs/jnigen/lib/src/bindings/dart_generator.dart (hunk 1 above)
Comment (HosseinYousefi) [reply pkgs/jnigen/lib/src/bindings/dart_generator.dart:796]: Good suggestion, rewriting the logic made the code much better!
