### PR TITLE
[objective_c] Implement NSNumber methods for bool

### LINKED ISSUE #1234: [jnigen] Detect mvn missing error and fail gracefully
```
$ dart --enable-experiment=native-assets run jnigen --config jnigen_config.yaml 
(jnigen) INFO: Building ApiSummarizer component. This might take some time. The build will be cached for subsequent runs.
(jnigen) INFO: execute mvn compile --batch-mode --update-snapshots -f /Users/dacoharkes/.pub-cache/hosted/pub.dev/jnigen-0.9.3/java/pom.xml

/bin/sh: mvn: command not found

maven exited with 127
Unhandled exception:
PathNotFoundException: Deletion failed, path = './.dart_tool/jnigen/target' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:180:7)
<asynchronous suspension>
#2      buildApiSummarizer (package:jnigen/src/tools/build_summarizer.dart:51:5)
<asynchronous suspension>
#3      buildSummarizerIfNotExists (package:jnigen/src/tools/build_summarizer.dart:74:5)
<asynchronous suspension>
#4      generateJniBindings (package:jnigen/src/generate_bindings.dart:26:3)
<asynchronous suspension>
#5      main (file:///Users/dacoharkes/.pub-cache/hosted/pub.dev/jnigen-0.9.3/bin/jnigen.dart:18:3)
<asynchronous suspension>
```

We should probably not fail with deletion failed if mvn is missing.

### PR DESCRIPTION
**Pull request by knopp**
Adds `bool.toNSNumber()` extension method, `NSNumber.isBool` check and add converter support for bool.

## Related Issues

*List which issues are fixed by this PR. Use the syntax `Fixes #1234`.*

## PR Checklist

- [x] I’ve reviewed the [contributor guide](https://github.com/dart-lang/native/blob/main/CONTRIBUTING.md) and applied the relevant portions to this PR.
- [x] I've run `dart tool/ci.dart --all` locally and resolved all issues identified. This ensures the PR is formatted, has no lint errors, and ran all code generators. This applies to the packages part of the toplevel `pubspec.yaml` workspace.
- [x] All existing and new tests are passing. I added new tests to check the change I am making.
- [x] The PR is actually solving the issue. PRs that don't solve the issue will be closed. Please be respectful of the maintainers' time. If it's not clear what the issue is, feel free to ask questions on the GitHub issue before submitting a PR.
- [x] I have updated `CHANGELOG.md` for the relevant packages. (Not needed for small changes such as doc typos).
- [x] I have [updated the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change) if necessary.

### CODE REVIEW

**Comment by knopp** [comment]
Not sure why there are so many changes in generated bindings, is that expected?

**Review by liamappelbe — COMMENTED** [review]
I think technically renaming `NSNumberIsFloat` is a breaking change, even though it's unlikely to actually affect any users. But just to be safe, it would be better to add a separate `NSNumberIsBool` interface.

As for the bindings diffs, no, they're not expected. I suspect you're using a different version of xcode than me and the github bot. Some of the diffs look problematic too. Are you able to update your xcode?

**Comment by knopp** [comment]
@liamappelbe, I reverted to `NSNumberIsFloat`, regenerated files with latest Xcode. Seems better.

File: pkgs/objective_c/test/nsnumber_test.dart [hunk 1]
```diff
@@ -19,6 +19,7 @@ void main() {
       expect(n.doubleValue, 1.23);
       expect(n.numValue, isA<double>());
       expect(n.numValue, 1.23);
+      expect(n.isFloat, isTrue);
```
Comment (liamappelbe) [inline pkgs/objective_c/test/nsnumber_test.dart:22]: Add a quick test for `n.isBool`?

File: pkgs/objective_c/lib/src/objective_c_bindings_generated.dart [hunk 2]
```diff
@@ -2106,8 +2106,7 @@ enum NSAttributedStringMarkdownParsingFailurePolicy {
 /// macOS: introduced 12.0.0
 extension type NSAttributedStringMarkdownParsingOptions._(
   objc.ObjCObject object$
-)
-    implements objc.ObjCObject, NSObject, NSCopying {
+) implements objc.ObjCObject, NSObject, NSCopying {
```
Comment (liamappelbe) [inline pkgs/objective_c/lib/src/objective_c_bindings_generated.dart]: I've seen this diff in a few of my PRs too. I think it's is caused by a mismatch between the Dart version on github CI, and our local version. It causes the [formatting CI step to fail](https://github.com/dart-lang/native/actions/runs/25071891088/job/73497228450?pr=3331). It will probably go away if you update to the latest version of Dart, or since it's such a minor diff you can just revert it manually.

**Review by liamappelbe — COMMENTED** [review]
Looks good. Almost ready to land.

File: pkgs/objective_c/lib/src/objective_c_bindings_generated.dart (hunk 2 above)
Comment (knopp) [reply pkgs/objective_c/lib/src/objective_c_bindings_generated.dart]: Reverted.

File: pkgs/objective_c/test/nsnumber_test.dart (hunk 1 above)
Comment (knopp) [reply pkgs/objective_c/test/nsnumber_test.dart:22]: Done.

**Review by liamappelbe — APPROVED** [review]
